apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: amplitude-proxy-alerts
  namespace: dataplattform
  labels:
    team: dataplattform
spec:
  groups:
    - name: amplitude-proxy-system-alerts
      rules:
      - alert:  Amplitude-proxy nede
        expr: count(kube_pod_container_status_running{container="amplitude-proxy", namespace="dataplattform"}) < 2
        for: 2m
        annotations:
          consequence: Application is unavailable
          action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
          summary: |-
            App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}.
        labels:
          namespace: dataplattform
          severity: critical

      - alert: høy feilrate i collect auto endepunkte
        expr: sum(increase(collect_auto_endpoint{message="failed_proxy_events"}[1m])) > 50
        for: 3m
        annotations:
          consequence: Application is experiencing high traffic for the the collect auto endpoint
          action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
          summary: |-
            App {{ $labels.app }} har høy feilrate bruk i namespace {{ $labels.kubernetes_namespace }}
        labels:
          namespace: dataplattform
          severity: warning

      - alert: høy feilrate i collect endepunkte
        expr: sum(increase(collect_endpoint{message="failed_proxy_events"}[1m])) > 50
        for: 3m
        annotations:
          consequence: Application is experiencing high traffic for the collect endpoint
          action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så mye feil"
          summary: |-
            App {{ $labels.app }} har høy feilrate bruk i namespace {{ $labels.kubernetes_namespace }}
        labels:
          namespace: dataplattform
          severity: warning          

      - alert: Lav trafikk (respose code 200 er < 1 ) for collect auto
        expr: sum(irate(collect_auto_endpoint{message="success"}[1d])) < 1
        for: 3m
        annotations:
          consequence: Application is experiencing low success traffic for collect auto
          action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så lav traffic"
          summary: |-
            App {{ $labels.app }} har lav traffik i namespace {{ $labels.kubernetes_namespace }}
        labels:
          namespace: dataplattform
          severity: critical

      - alert: Lav trafikk (respose code 200 er < 1 ) for collect
        expr: sum(irate(collect_endpoint{message="success"}[1d])) < 1
        for: 3m
        annotations:
          consequence: Application is experiencing low success traffic for collect
          action: "Sjekk loggene til app {{ $labels.log_app }} i namespace {{ $labels.log_namespace }}, for å se hvorfor det er så lav traffic"
          summary: |-
            App {{ $labels.app }} har lav traffik i namespace {{ $labels.kubernetes_namespace }}
        labels:
          namespace: dataplattform
          severity: critical