apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: dataplattform
  name: amplitude-proxy
  namespace: dataplattform
spec:
  accessPolicy:
    outbound:
      external:
        - host: api.eu.amplitude.com
        - host: cdn.amplitude.com
  image: {{image}}
  port: 4242
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-infrastructure
  liveness:
    path: /health/is-alive
    initialDelay: 5
    timeout: 1
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /health/is-ready
    initialDelay: 30
    timeout: 1
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 2500m
      memory: 4Gi
    requests:
      cpu: 200m
      memory: 256Mi
  ingresses:
    - "https://amplitude.nav.no"
  env:
    - name: AMPLITUDE_URL
      value: https://api.eu.amplitude.com
    - name: KAFKA_INGRESS_TOPIC
      value: dataplattform.ingress-topic-v2
    - name: PROJECT_KEYS_FILE
      value: /var/run/secrets/project-keys.json
  filesFrom:
    - secret: project-keys
